In [1]:
print("abc")

abc


In [4]:
a = [2,3,4,56]
type(a)


list

In [6]:
import numpy as np
a1 = np.array([8,6,3,4,5])
type(a1)

numpy.ndarray

In [13]:
a2 = np.array([8,6,3,4,5,"abc"])
a2

array(['8', '6', '3', '4', '5', 'abc'], dtype='<U21')

In [ ]:
# different way to create array 1. arange(start , stop, step )


In [14]:
a3 = np.arange(1,9,2)
a3

array([1, 3, 5, 7])

In [18]:
a4 = np.arange(1,8,2)
a4

array([1, 3, 5, 7])

In [17]:
type(a4)

numpy.ndarray

In [19]:
a4.dtype

dtype('int64')

In [22]:
a5 = np.arange(1,9,0.8)
a5

array([1. , 1.8, 2.6, 3.4, 4.2, 5. , 5.8, 6.6, 7.4, 8.2])

linspace

In [23]:
a1 = np.linspace(1,9,12)
a1

array([1.        , 1.72727273, 2.45454545, 3.18181818, 3.90909091,
       4.63636364, 5.36363636, 6.09090909, 6.81818182, 7.54545455,
       8.27272727, 9.        ])

In [24]:
a1 = np.linspace(1,9)
a1

array([1.        , 1.16326531, 1.32653061, 1.48979592, 1.65306122,
       1.81632653, 1.97959184, 2.14285714, 2.30612245, 2.46938776,
       2.63265306, 2.79591837, 2.95918367, 3.12244898, 3.28571429,
       3.44897959, 3.6122449 , 3.7755102 , 3.93877551, 4.10204082,
       4.26530612, 4.42857143, 4.59183673, 4.75510204, 4.91836735,
       5.08163265, 5.24489796, 5.40816327, 5.57142857, 5.73469388,
       5.89795918, 6.06122449, 6.2244898 , 6.3877551 , 6.55102041,
       6.71428571, 6.87755102, 7.04081633, 7.20408163, 7.36734694,
       7.53061224, 7.69387755, 7.85714286, 8.02040816, 8.18367347,
       8.34693878, 8.51020408, 8.67346939, 8.83673469, 9.        ])

logspace



In [25]:
np.logspace(1,9,8)

array([1.00000000e+01, 1.38949549e+02, 1.93069773e+03, 2.68269580e+04,
       3.72759372e+05, 5.17947468e+06, 7.19685673e+07, 1.00000000e+09])

In [26]:
np.logspace(1,9)

array([1.00000000e+01, 1.45634848e+01, 2.12095089e+01, 3.08884360e+01,
       4.49843267e+01, 6.55128557e+01, 9.54095476e+01, 1.38949549e+02,
       2.02358965e+02, 2.94705170e+02, 4.29193426e+02, 6.25055193e+02,
       9.10298178e+02, 1.32571137e+03, 1.93069773e+03, 2.81176870e+03,
       4.09491506e+03, 5.96362332e+03, 8.68511374e+03, 1.26485522e+04,
       1.84206997e+04, 2.68269580e+04, 3.90693994e+04, 5.68986603e+04,
       8.28642773e+04, 1.20679264e+05, 1.75751062e+05, 2.55954792e+05,
       3.72759372e+05, 5.42867544e+05, 7.90604321e+05, 1.15139540e+06,
       1.67683294e+06, 2.44205309e+06, 3.55648031e+06, 5.17947468e+06,
       7.54312006e+06, 1.09854114e+07, 1.59985872e+07, 2.32995181e+07,
       3.39322177e+07, 4.94171336e+07, 7.19685673e+07, 1.04811313e+08,
       1.52641797e+08, 2.22299648e+08, 3.23745754e+08, 4.71486636e+08,
       6.86648845e+08, 1.00000000e+09])

In [27]:
np.zeros(5,dtype="complex")

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

In [28]:
np.ones(5,dtype="str")

array(['1', '1', '1', '1', '1'], dtype='<U1')

2D ARRAY

COLLECTIOM OF ONE DIMENSIONAL ARRAY

In [30]:
a = np.array([22,33,44,55])

In [31]:
a

array([22, 33, 44, 55])

In [32]:
a.ndim

1

In [39]:
a = np.array([[22,33,44,55],[66,77,88,99],[96,65,64,69]])

In [40]:
a

array([[22, 33, 44, 55],
       [66, 77, 88, 99],
       [96, 65, 64, 69]])

In [41]:
a.ndim

2

In [42]:
a[1]

array([66, 77, 88, 99])

In [44]:
a[-1]

array([96, 65, 64, 69])

In [45]:
a[1][1:3]

array([77, 88])

In [46]:
a[1][1]

np.int64(77)

In [48]:
a[1:2,1:2]

array([[77]])

SLICING

In [50]:
a[0:2:1]

array([[22, 33, 44, 55],
       [66, 77, 88, 99]])

In [51]:
a[0:2:1,1:3:1]

array([[33, 44],
       [77, 88]])

In [52]:
a[ : :2]

array([[22, 33, 44, 55],
       [96, 65, 64, 69]])

In [55]:
a[ : :2 ,: : 3]

array([[22, 55],
       [96, 69]])

In [56]:
a

array([[22, 33, 44, 55],
       [66, 77, 88, 99],
       [96, 65, 64, 69]])

In [57]:
a.shape

(3, 4)

In [59]:
a.ravel()

array([22, 33, 44, 55, 66, 77, 88, 99, 96, 65, 64, 69])

In [61]:
a.size

12

In [62]:
a

array([[22, 33, 44, 55],
       [66, 77, 88, 99],
       [96, 65, 64, 69]])

In [63]:
a.reshape(6,2)

array([[22, 33],
       [44, 55],
       [66, 77],
       [88, 99],
       [96, 65],
       [64, 69]])

In [67]:
a.reshape(2,6)

array([[22, 33, 44, 55, 66, 77],
       [88, 99, 96, 65, 64, 69]])

arange() IT IS USEFOR CREATING A 2D ARRAY

In [70]:
np.arange(8).reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [72]:
np.linspace(1,20,20).reshape(5,4)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.],
       [17., 18., 19., 20.]])

In [76]:
a=np.arange(30).reshape(3,2,5)

In [77]:
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [78]:

a.ndim


3

In [79]:
a.shape

(3, 2, 5)

In [80]:
a.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

RESHAPE()

In [3]:
import numpy as np

In [4]:
a = np.arange(12)

In [5]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
a.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [7]:
a.reshape(2 ,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])